version: '2'

services:
  backup:
    container_name: backup
    image: mittax/lemp-backup
    volumes_from:
      - wwwdata
      - nginx
      - mariadb
      - php70
    volumes:
      - ./data/backups:/var/backups
    restart: always
    networks:
      development:
        ipv4_address: 172.16.238.6
        ipv6_address: 2001:3984:3989::6
  wwwdata:
    container_name: wwwdata
    image: mittax/lemp-wwwdata
    volumes:
      - ./data/www:/var/www
    restart: always
    networks:
      development:
        ipv4_address: 172.16.238.7
        ipv6_address: 2001:3984:3989::7
  nginx:
    container_name: nginx
    image: mittax/lemp-nginx
    volumes:
      - ./data/config/nginx:/etc/nginx
      - ./data/log/nginx:/var/log/nginx
    volumes_from:
      - wwwdata
    ports:
      - "8089:80"
    networks:
      development:
        ipv4_address: 172.16.238.8
        ipv6_address: 2001:3984:3989::8
    restart: always
  php70:
    container_name: php70
    image: mittax/lemp-php70
    image: mittax/lemp-php70
    environment:
      PHP_ENV: 'development'
      PHP_APCU_ENABLED: 'false'
      PHP_XDEBUG_ENABLED: 'false'
    volumes:
      - ./data/config/php/pool70/:/etc/php/7.0/fpm/pool.d
      - ./data/config/php/ini70/development.ini:/etc/php/mods-available/development.ini
      - ./data/config/php/ini70/production.ini:/etc/php/mods-available/production.ini
      - ./data/log/php70:/var/log/php
    volumes_from:
      - wwwdata
    restart: always
    networks:
      development:
          ipv4_address: 172.16.238.13
          ipv6_address: 2001:3984:3989::13
  mariadb:
    container_name: mariadb
    image: mittax/lemp-mariadb
    volumes:
      - ./data/config/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./data/log/mariadb:/var/log/mysql
      - ./data/mariadb:/var/lib/mysql
    environment:
      DB_ADMIN_PASS: pass
    ports:
      - "3308:3306"
    restart: always
    networks:
      development:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./data/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "63799:6379"
    restart: always
    networks:
      development:
        ipv4_address: 172.16.238.11
        ipv6_address: 2001:3984:3989::11

  rabbit1:
    container_name: rabbitmq
    image: mittax/lemp-rabbitmq
    hostname: rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
    networks:
      development:
        ipv4_address: 172.16.238.12
        ipv6_address: 2001:3984:3989::12

networks:
  development:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1