<?php

namespace EmoticoBundle\EmoticoBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use AppBundle\Entity\User;


class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function attach(User $user)
    {
        // TODO: Implement attach() method.
    }

    public function detach(User $user)
    {
        // TODO: Implement detach() method.
    }

    public function toggle(User $user)
    {
        // TODO: Implement toggle() method.
    }

}
