<?php

namespace Mittax\MessageBundle\Repository;

/**
 * MessageBoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageBoxRepository extends \Doctrine\ORM\EntityRepository
{
}
